baseURL = 'https://kylorend3r.github.io/'
languageCode = 'en-us'
title = 'kylorend3r Blog'
theme = 'PaperMod'

[params]
  env = 'production'
  title = 'kylorend3r Blog'
  description = 'A blog about databases, PostgreSQL, and software engineering'
  keywords = ['blog', 'postgresql', 'database', 'software engineering']
  author = 'kylorend3r'
  images = ['/og-image.png']
  
  # Social Icons
  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/kylorend3r'
  
  # Theme options
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = true
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  
  # Home page: Regular mode (shows posts directly)
  # Posts will be displayed directly on the home page
  mainSections = ['posts']

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 20
